package hight.sa.mapper;

import hight.sa.model.FileUploadLog;
import hight.sa.model.FileUploadLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileUploadLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload_log
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    long countByExample(FileUploadLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload_log
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    int deleteByExample(FileUploadLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload_log
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload_log
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    int insert(FileUploadLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload_log
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    int insertSelective(FileUploadLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload_log
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    List<FileUploadLog> selectByExample(FileUploadLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload_log
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    FileUploadLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload_log
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    int updateByExampleSelective(@Param("record") FileUploadLog record, @Param("example") FileUploadLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload_log
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    int updateByExample(@Param("record") FileUploadLog record, @Param("example") FileUploadLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload_log
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    int updateByPrimaryKeySelective(FileUploadLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload_log
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    int updateByPrimaryKey(FileUploadLog record);
}