package hight.sa.mapper;

import hight.sa.model.FileInfo;
import hight.sa.model.FileInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    long countByExample(FileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    int deleteByExample(FileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    int insert(FileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    int insertSelective(FileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    List<FileInfo> selectByExample(FileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    FileInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    int updateByExampleSelective(@Param("record") FileInfo record, @Param("example") FileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    int updateByExample(@Param("record") FileInfo record, @Param("example") FileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    int updateByPrimaryKeySelective(FileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    int updateByPrimaryKey(FileInfo record);
}