package hight.sa.model;

public class FileUploadLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload_log.id
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload_log.file_name
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    private Integer fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload_log.file_type
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    private Integer fileType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload_log.file_owner
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    private Integer fileOwner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload_log.status
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload_log.uploaded_at
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    private Integer uploadedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_upload_log.id
     *
     * @return the value of file_upload_log.id
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_upload_log.id
     *
     * @param id the value for file_upload_log.id
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_upload_log.file_name
     *
     * @return the value of file_upload_log.file_name
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    public Integer getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_upload_log.file_name
     *
     * @param fileName the value for file_upload_log.file_name
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    public void setFileName(Integer fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_upload_log.file_type
     *
     * @return the value of file_upload_log.file_type
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    public Integer getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_upload_log.file_type
     *
     * @param fileType the value for file_upload_log.file_type
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    public void setFileType(Integer fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_upload_log.file_owner
     *
     * @return the value of file_upload_log.file_owner
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    public Integer getFileOwner() {
        return fileOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_upload_log.file_owner
     *
     * @param fileOwner the value for file_upload_log.file_owner
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    public void setFileOwner(Integer fileOwner) {
        this.fileOwner = fileOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_upload_log.status
     *
     * @return the value of file_upload_log.status
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_upload_log.status
     *
     * @param status the value for file_upload_log.status
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_upload_log.uploaded_at
     *
     * @return the value of file_upload_log.uploaded_at
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    public Integer getUploadedAt() {
        return uploadedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_upload_log.uploaded_at
     *
     * @param uploadedAt the value for file_upload_log.uploaded_at
     *
     * @mbg.generated Tue Mar 21 23:20:10 CST 2017
     */
    public void setUploadedAt(Integer uploadedAt) {
        this.uploadedAt = uploadedAt;
    }
}